// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedStar.WebService.Models;

namespace RedStar.WebService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RedStar.WebService.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Born")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Born = 1995,
                            FirstName = "Dejan",
                            Height = 202,
                            LastName = "Davidovac",
                            Number = 7,
                            PhotoPath = "images/dejan.png",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 2,
                            Born = 1993,
                            FirstName = "Luka",
                            Height = 206,
                            LastName = "Mitrovic",
                            Number = 9,
                            PhotoPath = "images/luka.png",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 3,
                            Born = 1989,
                            FirstName = "Branko",
                            Height = 195,
                            LastName = "Lazic",
                            Number = 10,
                            PhotoPath = "images/branko.png",
                            Position = "Guard"
                        },
                        new
                        {
                            Id = 4,
                            Born = 1994,
                            FirstName = "Ognjen",
                            Height = 200,
                            LastName = "Dobric",
                            Number = 13,
                            PhotoPath = "images/ognjen.png",
                            Position = "Guard"
                        },
                        new
                        {
                            Id = 5,
                            Born = 1986,
                            FirstName = "Marko",
                            Height = 203,
                            LastName = "Simonovic",
                            Number = 19,
                            PhotoPath = "images/marko.png",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 6,
                            Born = 1994,
                            FirstName = "Nikola",
                            Height = 191,
                            LastName = "Ivanovic",
                            Number = 20,
                            PhotoPath = "images/nikola.png",
                            Position = "Guard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
